### ISSUE TITLE
General improvements to test templates

### ISSUE THREAD

**Issue by mecha** [Dhii/bootstrap#15]
Problems in current test templates:

* The assertion message needs to be "A valid instance of the test subject could not be created."
* Use a `TEST_SUBJECT_CLASSNAME` constant in ~unit~ test template
* ~Rename test classes with mention of either "Func" or "Unit" as appropriate, to avoid annoying IDE duplicate class declaration warnings.~

**Comment by XedinUnknown** [comment]
Done.
