### ISSUE TITLE
CodeClimate Disallows Methods With Underscore

### ISSUE THREAD

**Issue by XedinUnknown** [Dhii/bootstrap#20]
The `phpmd` engine of CodeClimate keeps reporting numerous PSR violations where method names begin with an underscore, although this is not strictly disallowed (the word used in the PSR is "SHOULD"). Currently, the `phpmd` config document that is bundled with this bootstrap attempts to switch off this check. However, it doesn't seem to be working.

This is because there is a mistake in the config, using `CamelCasePropertyName` instead of `CamelCaseMethodName`, as advised by CodeClimate support. Also, it may be that inclusion of the whole controversial ruleset overrides any fine-tuning done after, although this is unexplained.

NOTHING WORKS. Remove the [controversial rule](https://github.com/Dhii/bootstrap/blob/release/0.2/phpmd.xml#L14), and keep the [exception](https://github.com/Dhii/bootstrap/blob/release/0.2/phpmd.xml#L22) just in case.

**Comment by mecha** [comment]
Should the exception be changed to `CamelCaseMethodName`?

**Comment by XedinUnknown** [comment]
Indeed. Thank you for pointing this out.

**Comment by XedinUnknown** [comment]
Fixed by ad5282279691410d3b972d9b8ad558a960bbc96e.
