### ISSUE TITLE
Switch Badges To Reflect Develop Status

### ISSUE THREAD

**Issue by XedinUnknown** [Dhii/bootstrap#22]
It has been decided that from now on the repositories' main branch should be `develop`.

Change all status indicators to represent the project status on the `develop` branch where applicable and possible.

**Comment by mecha** [comment]
Can't find any documentation regarding Code Climate badges. But an excerpt shown in a Google search ("refresh your default branch") suggests that it uses the repository's default branch.

As for Packagist badges, does it make sense to change it to `develop`? I feel like it should reflect the latest stable version.

This leaves just Travis CI badges, which can be easily changed to reflect build status for a different branch.

**Comment by XedinUnknown** [comment]
AFAIK, CC considers the default branch as the main one.

Maybe can leave the Packagist badge alone, because this badge reflects the latest stable version. If we need the latest unstable int eh future, we can add the relevant badge
[![Latest Unstable Version](https://poser.pugx.org/dhii/invoker-interface/v/unstable)](https://packagist.org/packages/dhii/invoker-interface)

With regard to the CI badges, this is perhaps what can be changed: the `master` branch should _always_ pass; it's the nightly that is of most interest, IMHO. Thoughts?

**Comment by mecha** [comment]
Agree for CC.

Agree for Packagist.

For CI, yes I share your opinion. In case I wasn't clear in my previous comment, want I wanted to convey was that Travis badge URLs accept a GET parameter to specify the branch, so it's easy to switch the branch for a badge.

**Comment by XedinUnknown** [comment]
Go for it.

**Comment by mecha** [comment]
Went for it ☝️

**Comment by XedinUnknown** [comment]
Done.
