### ISSUE TITLE
Better Autoload Namespace Deduction

### ISSUE THREAD

**Issue by mecha** [Dhii/bootstrap#23]
The autoload namespace is currently auto defaulted to the project name without spaces. For instance, a project called "State Machine Interface" gives a default autoload namespace of `Dhii\StateMachineInterface`.

## Proposal 

After carefully looking at the package names used in Dhii, we can use only the first word in the project name. Some examples:

* Type Interface = `Dhii\Type`
* Validation Abstract = `Dhii\Validation`
* Iterator Base = `Dhii\Iterator`

While not accurate 100% of the time, it _does_ manage to deduce the desired autoload namespace _most_ of the time. Certain packages such as "State Machine Interface" would produce `Dhii\State`, which is still incorrect.

**Comment by XedinUnknown** [comment]
Add a setting that determines the max number of words from the name to use in the namespace, defaulting to `1`, and use that setting to proceed as described.

**Comment by XedinUnknown** [comment]
Done.
