### ISSUE TITLE
Add PHPStorm files to Git ignore list

### ISSUE THREAD

**Issue by mecha** [Dhii/bootstrap#24]
Certain PHPStorm files are not meant to be committed and are user-specific. These are:

* `.idea/workspace.xml`
* `.idea/tasks.xml`
* `.idea/dictionaries/`

Others are simply not applicable for certain projects, such as `.idea/vagrant.xml` - but such cases can just be added to the ignore list manually.

**Comment by XedinUnknown** [comment]
Done.
